name: Deploy to production
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      # - name: Set RELEASE_TAG env
      #   run: echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Dispatch release
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: ${{ secrets.REPO_DISPATCH_PATH }}
          event-type: coopcycle-release
          # client-payload: '{"tag": "${{ env.RELEASE_TAG }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
